### ISSUE TITLE
Epic: Backend & ML

### ISSUE THREAD

**Issue by wrynearson** [developmentseed/wb-agrifood-backend#1]
```[tasklist]
### Tasks
- [x] https://github.com/developmentseed/wb-agrifood-backend/issues/4
- [ ] https://github.com/developmentseed/wb-agrifood-backend/issues/2
- [ ] https://github.com/developmentseed/wb-agrifood-backend/issues/3
```
